name: blood-box
description: A GitHub Action to create a blood box
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      repository: 'listennn08/blood-box'
  - uses: actions/setup-go@v4
    with:
      go-version: '1.21.x' 
  - name: Install dependencies
    run: go get .
    shell: bash
  - name: Update gist
    run: go run main.go
    shell: bash