name: Update Gist
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *
permissions: write-all
jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install
        run: npx pnpm i --store=node_modules/.pnpm-store
      - name: update
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLOOD_API_URL: ${{ secrets.BLOOD_API_URL }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: npm run dev
      
