name: Update Gist
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: listennn08/blood-box@main
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BLOOD_API_URL: ${{ secrets.BLOOD_API_URL }}
          GIST_ID: ${{ secrets.GIST_ID }}
